name: Continuous Integration (PEP8 Lint + pytest)

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pipenv & sync
      run: |
        cd triple-dungeon
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv lock
        pipenv sync
    - name: Linting
      run: |
        pip install pycodestyle
        # PyCharm sets line length at 120 chars
        pycodestyle . --count --statistics --max-line-length=120
    - name: Test with pytest
      run: |
        pip install pytest
        pytest tests.py